version: '3.1'

services:
  api: 
    build: ./server
    volumes:
      - ./server:/usr/src/app
    command: bash -c "if [ ! -d 'node_modules' ]; then yarn; fi; yarn run dev"
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: always

volumes:
  redis-data: