version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      PORT: 3000
      CLIENT_NAME: http://localhost:4200
      CALLBACK: http://localhost:3000
      GOOGLE_SECRET_CLIENT:
      GOOGLE_CLIENT_ID:
      SECRET:
    ports: 
      - 3000:3000
      - 9230:9230