version: '3.1'

services:
  api: 
    build: .
    volumes:
      - .:/usr/src/app
    command: bash -c "if [ ! -d 'node_modules' ]; then yarn; fi; yarn start"
    ports:
      - 80:80
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 80
      CLIENT_NAME: https://mihorarioun.web.app
      GOOGLE_SECRET_CLIENT: CgWGUp9zeNqdwSvdKnkAonvr
      GOOGLE_CLIENT_ID: 119902822900-pv2v7cssdnq4vpobtn0moirt0g95ipnc.apps.googleusercontent.com
      CALLBACK: https://mihorarioun.web.app
      SECRET:
      CRYPTR_SECRET:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    restart: always