version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports: 
      - 5000:5000
      - 9230:9230
    environment:
      PORT: 5000
      CLIENT_NAME: http://localhost:4200
      CALLBACK: http://localhost:5000
      UNINORTE_GRAPHQL: https://uninorte-graphql.herokuapp.com
      GOOGLE_SECRET_CLIENT:
      GOOGLE_CLIENT_ID:
      SECRET: