name: Build and deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: client
        run: npm install
      - name: Adding firebase Api Key
        working-directory: client
        run: npm run build:update ${{ secrets.FIREBASE_API_KEY }}
      - name: Build
        working-directory: client
        run: npm run build:prod
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        working-directory: client
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
