name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd client
          npm install
      - name: Build
        run: |
          cd client
          alias ng="./node_modules/angular-cli/bin/ng"
          ng build --prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy client to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Login to Heroku
        uses: actions/heroku@1.0.0
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Push
        uses: actions/heroku@1.0.0
        with:
          args: cd server && container:push -a $(basename $GITHUB_REPOSITORY) web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Release
        uses: actions/heroku@1.0.0
        with:
          args: cd server && container:release -a $(basename $GITHUB_REPOSITORY) web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
